topics:
-
  name    : navigation
  topic   : nav_cmd_vel
  timeout : 0.5
  priority: 10  # 10
-
  name    : joystick
  topic   : joy_cmd_vel
  timeout : 0.5
  priority: 100
-
  name    : keyboard
  topic   : key_vel
  timeout : 0.5
  priority: 90
-
  name    : tablet
  topic   : tab_vel
  timeout : 0.5
  priority: 100