global_costmap:
  global_frame: map
  robot_base_frame: rslidar

  update_frequency: 2.0
  publish_frequency: 2.0
  # transform_tolerance: 0.5

  static_map: true
  rolling_window: true

  width: 100.0
  height: 100.0
  resolution: 0.05