local_costmap:
  #We'll publish the voxel grid used by this costmap
  publish_voxel_map: true

  #Set the global and robot frames for the costmap
  global_frame: map
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 10.0
  publish_frequency: 5.0

  #We'll configure this costmap to be a rolling window... meaning it is always
  #centered at the robot
  static_map: false
  rolling_window: true
  # width: 10.0
  # height: 10.0
  resolution: 0.02
  transform_tolerance: 5.0
  map_type: costmap

  plugins:
    # - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    # - {name: sonar_layer,         type: 'range_sensor_layer::RangeSensorLayer'}
    - {name: inflation_layer,     type: 'costmap_2d::InflationLayer'}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.8 #0.8 #0.5 #1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

  obstacle_layer:
    enabled: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0
    obstacle_range: 3.0                     #10~11m
    raytrace_range: 5.0
    # inflation_radius: 0.45
    combination_method: 0
    observation_sources: laser_scan_sensor
    track_unknown_space: true
    inf_is_valid: true
    use_global_mark_threshold: false  #This parameter if set true, the local observation_sources clear_threshold and mark_threshold will not effect
  
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    unknown_threshold: 15
    mark_threshold: 0
    clear_threshold: 0
    publish_voxel_map: true
    footprint_clearing_enabled: true

    laser_scan_sensor:
      data_type: LaserScan
      topic: rslidar_laserscan
      marking: true
      clearing: true
      inf_is_valid: true
      mark_threshold: 0
      clear_threshold: 0
      expected_update_rate: 15
      min_obstacle_height: 0.12
      max_obstacle_height: 0.25
      obstacle_range: 5.0                     #10~11m
      raytrace_range: 8.0

  # sonar_layer:
  #   enabled:            true
  #   clear_threshold:    0.2 #0.46
  #   inflate_cone:       0.3
  #   mark_threshold:     0.55
  #   topics: ["/Ultrasound1","/Ultrasound2","/Ultrasound3","/Ultrasound4","/Ultrasound5","/Ultrasound6","/Ultrasound7","/Ultrasound8"] #, "/Ultrasound3", "/Ultrasound4", "/Ultrasound5", "/Ultrasound2", ]   # "/Ultrasound7", "/Ultrasound8",
  #   clear_on_max_reading: true           