EBandPlannerROS:
  
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 3.1415
  max_vel_lin: 0.4
  min_vel_lin: 0.1
  max_vel_th: 0.3
  min_vel_th: 0.0
  max_rotational_acceleration: 3.5
  max_acceleration: 3.0

  differential_drive: true

  eband_min_relative_overlap: 0.5

  Ctrl_Rate: 10
  eband_internal_force_gain: 1.5
  eband_external_force_gain: 2.0
  num_iterations_eband_optimization: 4
  eband_equilibrium_relative_overshoot: 0.1
  k_damp: 3.5
  k_prop: 4.0

  rotation_correction_threshold: 2.0