local_costmap:
  global_frame: map  
  robot_base_frame: base_link

  update_frequency: 15.0
  publish_frequency: 5.0
  transform_tolerance: 0.5
  
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05

  include_dynamic_obstacles: true
  dynamic_obstacle_inflation_dist: 0.3

  plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: virtual_layer,       type: "virtual_wall::VirtualWall"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

    # - {name: static_layer, type: "costmap_2d::StaticLayer"}

  inflation_layer:
        enabled:              true
        cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
        inflation_radius:    0.5 #0.8 # 0.5 #1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

  obstacle_layer:
    enable: true
    # origin_z: 1.0
    # publish_voxel_map: true
    combination_method: 0.0
    observation_sources: scan
    scan: {
      sensor_frame: rslidar,
      data_type: LaserScan,
      topic: rslidar_laserscan,
      max_obstacle_height: 100.0,
      min_obstacle_height: -300.0,
      observation_persistance: 0.0,  #0.1
      #raytrace_range: 40.0,
      #obstacle_range: 3.0,
      expected_update_rate: 1,
      marking: true,
      inf_is_valid: true,
      clearing: true

    }
    
  
